# config/database.yml
# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: aesthetic_shop_development

test:
  <<: *default
  database: aesthetic_shop_test

production:
  <<: *default
  database: aesthetic_shop_production
  username: aesthetic_shop
  password: <%= ENV["AESTHETIC_SHOP_DATABASE_PASSWORD"] %>
